### ISSUE TITLE
Feature Request: Allow arrays for `postfix::config` values

### ISSUE THREAD

**Issue by jearls** [camptocamp/puppet-postfix#104]
The `postfix::config` defined type should allow arrays for values.

This...

```
postfix::config { 'mydestination':
    ensure => present ,
    value => [ $::fqdn , "smtp.${::domain}" , 'localhost' , 'localhost.localdomain' , "localhost.${::domain}" ]
}
```

should be the same as:

```
postfix::config { 'mydestination':
    ensure => present ,
    value => "$::fqdn smtp.${::domain} localhost localhost.localdomain localhost.${::domain}"
}
```

But the first one is easier to maintain, especially when pulling values from Hiera.

**Comment by jearls** [comment]
Pull request #106 opened for this

**Comment by ubellavance** [comment]
Will that allow me to set more than one reject_rbl_client parameter?

**Comment by jearls** [comment]
This won't _directly_ affect the `reject_rbl_client` parameter, because that's not a configuration variable by itself - it's a sub-parameter of the smtpd_client_restrictions.  WIthout this patch, the first example would work; with this patch, the second would also work.

    # works with existing camptocamp-postfix module
    postfix::config { 'smtpd_client_restrictions':
        ensure => present ,
        value => 'permit_mynetworks reject_rbl_client rbldomain1 reject_rblclient rbldomain2' ,
    }

    # works with PR#106
    postfix::config { 'smtpd_client_restrictions':
        ensure => present ,
        value => [
            'permit_my_networks' ,
            'reject_rbl_client rbldomain1' ,
            'reject_rbl_client rbldomain2' ,
        ]
    }

**Comment by ubellavance** [comment]
That is awesome!  I don't mind how it's done, I just wanted to be able to use more than 1 rbl.  Thanks!
