### ISSUE TITLE
remove configuration options that are not managed by puppet

### ISSUE THREAD

**Issue by micah** [camptocamp/puppet-postfix#107]
I've run into this frustrating problem with this module that I don't know how to solve, I'd be interested to hear if you have any good ideas for ways to fix this.

The problem is when you deploy this module, there may be configuration values that were previously set that aren't modified in the module deployment that can break things. For example, if you install postfix on a machine the installation might result in various postfix values being set (either by the package manager, or otherwise), and then when you deploy this module some of those values may be modified, and some not resulting in a non-deterministic postfix configuration which can be quite broken.

To ensure a clean configuration in the way that you intend it, the main.cf and master.cf that exist before the module is deployed should be removed or the values somehow unset. If the main.cf/master.cf already exist on the system, the contents of those files will have the values from this module set, but the others not touched. It would be good if all those could be cleared from the beginning.

I want to be able to remove configuration options that are not managed by puppet... is there some mechanism in augeas to purge unmanaged configurations or similar?

The only ways I can think of solving this are ugly, such as making an exec that removes the main.cf/master.cf and then touches some file to indicate that it has been purged and then the onlyif parameter is passed to check if that file exists.... another option would be to change completely from the postifx::config augeas methods to using templates, but this is also not a great solution either.

thanks for any ideas you might have!

**Comment by varac** [comment]
This would be great indeed.

**Comment by mrintegrity** [comment]
The workaround you suggested is implemented by someone else in this issue: https://github.com/camptocamp/puppet-postfix/issues/163
