### ISSUE TITLE
Document special value "direct" for relayhost in README.md

### ISSUE THREAD

**Issue by ingvarha** [camptocamp/puppet-postfix#120]
When acting as an mta (by setting mta to true), relayhost must be set to 'direct' for postfix to actually run as an independent mta, and not just relaying email to a smarthost. This is noted in the comments in the mta manifest, but that might be hard to find. Please add it to README.md as well.

**Comment by saimonn** [comment]
Thanks @ingvarha  for you comment.
Could you please make a PR for this ?
