### ISSUE TITLE
Allow to manage inet_protocols parameter

### ISSUE THREAD

**Issue by gothicx** [camptocamp/puppet-postfix#127]
It would be nice to be able to manage the inet_protocols parameter.

**Comment by igalic** [comment]
we do this via `postfix::config`

**Comment by raphink** [comment]
@igalic so this can be done without a new feature, correct?

**Comment by igalic** [comment]
@raphink correct.

**Comment by raphink** [comment]
I'll consider this a question and close then. Thank you @igalic.
