### ISSUE TITLE
master.cf not being managed when specifying master params

### ISSUE THREAD

**Issue by esarakaitis** [camptocamp/puppet-postfix#128]
`include postfix
postfix::config {
  'master_smtp': value  => 'smtp inet  n - n - - smtpd',
}
`
does not take effect in the master.cf... as the 127.0.0.1:smtp value still persists... thoughts?

**Comment by esarakaitis** [comment]
`include postfix
postfix::config {
  'smtp_listen': ensure => present, value => 'all',
}
`

postconf: warning: /etc/postfix/main.cf: unused parameter: smtp_listen=all

**Comment by heavyengineer** [comment]
I think it's pretty counter intuitive to set the master.cf to 127.0.0.1 for smtpd listening ports, especially when the user (i.e. me) expects a change in main.cf for inet_networks to be implemented. It took quite a while to debug that regardless what inet_interfaces is set to in main.cf, master.cf will still have 127.0.0.1 and override whatever you do. 
I got around this by setting manage_conffiles to false but this will only work where you don't want puppet to actually do stuff to the master.cf so isn't really a solution for everyone.
Maybe if the docs were just a little clearer that by default changing inet_interfaces won't do anything until you also change master.cf.
