### ISSUE TITLE
Don't force catchall-address in virtual.db

### ISSUE THREAD

**Issue by buschsalat** [camptocamp/puppet-postfix#131]
Hi,

the satellite.pp enforces the creation of a host-specific resource in line 42:  "@${postfix::myorigin}"
Please make this optional. There are valid reasons for not configuring a catchall-address on a satellite.
In the meantime I have workaround that by creating a custom virtual.db-file. Meaning, the original will still be in the filesystem, unused. That's ok but I like it clean ... :)

Regards

**Comment by raphink** [comment]
Thanks for reporting. I'd welcome a PR for that feature.
