### ISSUE TITLE
Can't redeclare virtual_alias_maps postfix setting

### ISSUE THREAD

**Issue by buschsalat** [camptocamp/puppet-postfix#132]
Please see #131. I can't overwrite the virtual_alias_maps setting via hiera, because it is already declared in mta.pp in line 52. Meaning, the workaround in the mentioned issue does not work.

What I want to do (some.yaml):
postfix::config:
  'virtual_alias_maps':
    value: 'hash:PATH'

Some for transport file.

Looking at mta.pp and init.pp, a fix would be to add $virtual_alias_maps and $transport_maps to the postfix class in init.pp and change mta.pp accordingly. (see $mydestination in postfix::mta class)

**Comment by devwwb** [comment]
A workaround that works here is to comment postfix::mta and then add the conf provided by ::mta with postfix::conf and postfix:

#postfix::mta: true
postfix::relayhost: ''
postfix::mydestination: "%{::fqdn}, localhost.%{::domain}, localhost, localhost.localdomain"
postfix::myorigin: '%{::fqdn}'
postfix::config:
  'virtual_alias_maps':
    ensure: 'present'
    value: 'ldap:/etc/postfix/ldap/virtual_mailbox_forward.cf'
