### ISSUE TITLE
Error: /Stage[main]/Postfix::Satellite/Postfix::Virtual[@$mydomain]/Augeas[Postfix virtual - @$mydomain]: Could not evaluate

### ISSUE THREAD

**Issue by mimmus** [camptocamp/puppet-postfix#145]
Using simple "Satellite" configuration:

    inet_interfaces: loopback-only
    mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
    myorigin: $mydomain
    relayhost: smtp.cervedgroup.com
    satellite: true

I get this error:

Error: /Stage[main]/Postfix::Satellite/Postfix::Virtual[@$mydomain]/Augeas[Postfix virtual - @$mydomain]: Could not evaluate: Saving failed, see debug

Using:

    satellite: false
    mta: true

I get no errors.

Distribution is Red Hat 7.2.

**Comment by raphink** [comment]
Can you launch with `--debug` and post the Augeas debug information please?

**Comment by mimmus** [comment]
[augeas-debug.txt](https://github.com/camptocamp/puppet-postfix/files/432775/augeas-debug.txt)

**Comment by raphink** [comment]
Thank you. The important part here will be:

```
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): sending command 'set' with params ["/files/etc/postfix/virtual/pattern[. = '@$mydomain']", "@$mydomain"]
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): sending command 'set' with params ["/files/etc/postfix/virtual/pattern[. = '@$mydomain']/destination", "root"]
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): Put failed on one or more files, output from /augeas//error:
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): /augeas/files/etc/postfix/virtual/error = put_failed
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): /augeas/files/etc/postfix/virtual/error/path = /files/etc/postfix/virtual
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): /augeas/files/etc/postfix/virtual/error/lens = /usr/share/augeas/lenses/dist/postfix_virtual.aug:51.10-.47:
Debug: Augeas[Postfix virtual - @$mydomain](provider=augeas): /augeas/files/etc/postfix/virtual/error/message = Malformed child node 'pattern'
```

Can you show what your `/etc/postfix/virtual` file looks like please?

**Comment by raphink** [comment]
`$mydomain` is not valid as a pattern as far as the lens is concerned (because of the `$`).

The lens accepts patterns matching `/[A-Za-z0-9@\*.+=-]+/` only.

 Should it be valid?

**Comment by mimmus** [comment]
This is the default /etc/postfix/virtual, only commented lines:
[postfix-virtual.txt](https://github.com/camptocamp/puppet-postfix/files/432843/postfix-virtual.txt)

Yes, it is valid:
http://www.postfix.org/postconf.5.html#myorigin

**Comment by raphink** [comment]
I don't see where it says that `$myorigin` is valid as a pattern in `virtual`. Can you be more specific?

**Comment by mimmus** [comment]
No, not in `virtual`, I used it in main.cf

**Comment by raphink** [comment]
But this issue is about using `$mydomain` in `/etc/postfix/virtual`.

**Comment by mimmus** [comment]
No; I started form a fresh install of OS and I applied config:

inet_interfaces: loopback-only
mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
myorigin: $mydomain
relayhost: smtp.cervedgroup.com
satellite: true

getting error above

**Comment by raphink** [comment]
OK, that's because https://github.com/camptocamp/puppet-postfix/blob/master/manifests/satellite.pp#L39 creates a `virtual` entry from `$myorigin`:

```puppet
  postfix::virtual { "@${postfix::myorigin}":
    ensure      => 'present',
    destination => 'root',
  }
```

and since you used `$mydomain` as the value for `$myorigin`, that fails.

**Comment by mimmus** [comment]
OK, I switched to:
` mta: true`
and it works flawlessy

**Comment by raphink** [comment]
So shall I mark this as a question and close?

**Comment by mimmus** [comment]
For me, OK. Unless you want to indagate furtherly.

Thank you very much
