### ISSUE TITLE
Hiera support

### ISSUE THREAD

**Issue by ubellavance** [camptocamp/puppet-postfix#152]
Hi,

Is there any plans to add hiera support to this module?

**Comment by igalic** [comment]
What kind of support, beyond what puppet delievers out of the box, are you thinking of?

**Comment by ubellavance** [comment]
Can we already use hiera with this module?  I'm using it but I use the traditionnal way.

**Comment by pckls** [comment]
You can pass parameterised classes Hiera data out of the box.

**Comment by ubellavance** [comment]
Ok, I'll try it out.  Is there documentation or examples?  Are they simply postifx::parameter?

**Comment by ubellavance** [comment]
According to #50, postfix::config , postfix::hash, postfix::transport and postfix::virtual are not hiera-compatible in this module.  I tested postfix::config and I can confirm.

**Comment by ksemaev** [comment]
As always with hiera I lost my mind trying to guess how to set parametrs. I know they should be working (I wasted 3 days once, guessing the syntax for another module), but I simply don't know how to set them. I try this, but nothing happens:
postfix::config:
 relay_domains:
  ensure: present
  value: 'smtp.example.com'
Maybe you have any guide - how to pass parametrs via hiera?

**Comment by ubellavance** [comment]
@ksemaev, see my previous post.  All postfix::config doesn't support hiera.

**Comment by Slm0n87** [comment]
+1

**Comment by DarkGigaByte** [comment]
+1

**Comment by PorkCharsui79** [comment]
+1 I was wondering about hiera support as well. There is no documentation on how to use and after trying anything and everything I get the feeling support for hiera isn't what it use to be. In an old version of the module you had the 'misc_settings' parameter which could be used to pass the data to the module from hiera, but you've removed that. I cannot get it to work properly anymore and would appreciate any help.

**Comment by jorhett** [comment]
config items can be sent by adding a hash `postfix::configs` which will all be processed by the defined type. See https://github.com/camptocamp/puppet-postfix/blob/master/manifests/init.pp#L91 for the hiera value assignment, and https://github.com/camptocamp/puppet-postfix/blob/master/manifests/init.pp#L141 for where it is used.

It would appear that the virtual and map types are intended to be used by the calling profile, as shown in this documentation: https://github.com/camptocamp/puppet-postfix#postfixvirtual. I believe that part of that reason is that this data could come from many sources / may not be unified under a single key.

However that doc doesn't mention that the "prep" work is done for you by `include postfix::mta`

Regardless, it people really wanted to unify this data under the postfix module, it would be a simple PR. My only question would be... wouldn't this data be best kept under mta?

**Comment by PorkCharsui79** [comment]
Thank you for your response. I managed to move more to hiera, but still not everything.

The point is we are trying to put all data, even our custom profiles, into hiera. We have so far managed to do this without using any of these types of statements for any modules:
```
include postfix
postfix::hash { '/etc/postfix/virtual':
  ensure => present,
}
postfix::config { 'virtual_alias_maps':
  ensure  => present,
  value   => 'hash:/etc/postfix/virtual',
}
```
We just "include" a module and do any customisation from hiera. This will be the first module for which we will have to make such a statement.

I can add the key 'postfix::mta: true' to hiera, that creates virtual(.db) and transport(.db), but then I still have to add the following statement to a module:
```
postfix::virtual { "@${fqdn}":
    ensure      => present,
    destination => 'nobody',
}
```
It also doesn't allow me to create **only** the virtual(.db) and make sure transport(.db) is absent.
 
Our 'profiles' modules reads module names to include from hiera and is not set up to accept the above statement. It just does 'include $modulename'. I might change our profiles module to accept the above type of statement, but I still think making every parameter in a module available with it's own hiera key is nicer. It would also give a more fine-grained control of the module. Just my 2 cents.

**Comment by jorhett** [comment]
The goal of the author was to make it possible to source your data from anywhere. Most large orgs have many pre-existing data sources.

To source your data from Hiera, you could instead add something like this to the profile:

```
$virtual_aliases = lookup('postfix::virtual_aliases', Hash, 'deep', {})
$virtual_aliases.each |$name, $values| {
  postfix::virtual { $name:
     ensure        => $values['ensure'],
     destination => $values['destination'],
  }
}
```

Then you can put all your entries in Hiera like so:
```
postfix::virtual_aliases:
  'user1':
    ensure: 'present'
    destination: 'nobody'
```

**Comment by PorkCharsui79** [comment]
Thanks for the advice! that's more or less what we decided on doing now, only we put it in a "wrapper" module for postfix specifically instead of the profile.
