### ISSUE TITLE
SPF checks

### ISSUE THREAD

**Issue by ju5t** [camptocamp/puppet-postfix#157]
I would like to include the SPF policy agent. I don't mind raising a pull request for it but I want to discuss it in a bit more detail first.

Right now the module uses flags such as `use_amavisd`. This is easy, relatively straight forward and you don't really have to think about it as a user. The SPF policy agent is a little different to a feature like Amavis. It needs to add a config line into in master.cf and it requires you to manage the `smtpd_recipient_restrictions` variable at a verify specific point. If the module does this for you it means you lose a lot of flexibility as a user because you can't manage that setting anymore.

It probably makes more sense to allow custom content in master.cf.common.erb or a new file. That would give you the opportunity to make the changes you need. 

If you want to use the SPF policy agent you need to install `pypolicyd-spf` on CentOS or `postfix-policyd-spf-python` on Ubuntu yourself as it's not installed as part of Postfix. That makes another discussion: should it include this or shouldn't it? 

I would make it as flexible as possible and leave out these packages and just allow custom content. What do you think?

**Comment by Tomelin** [comment]
Hi,

how i set 'use_amavisd' in this module?

**Comment by ju5t** [comment]
@Tomelin you're hijacking a different issue. If anything is unclear you should open a new issue instead.

**Comment by raphink** [comment]
@ju5t 	I think I'd welcome a `postfix::spf` class if you know how to implement it properly in the module.

**Comment by ju5t** [comment]
@raphink I'm afraid my time is a little limited. This wouldn't be on my todo list for the next few months probably. Although I think it can be useful to have a `postfix::spf` class we have our own implementation for now.

**Comment by raphink** [comment]
@ju5t 	understood and sorry for the long delay in responding. I'll keep this open in case someone is interested in implementing it.
