### ISSUE TITLE
Map files are not regenerated properly if the map file is removed

### ISSUE THREAD

**Issue by jearls** [camptocamp/puppet-postfix#161]
If a map file is removed without the source being removed, the map file is recreated as an empty file without the `postmap` command being executed.

**Comment by jearls** [comment]
The problem is that, if the source file, as generated by Puppet, is intact and unchanged, but the associated `.db` file removed, the code as it stands generates an empty `.db` file without generating its contents.

The solution, I believe, should be to remove `Exec["generate ${name}.db"]` from the `requires` parameter of the `file {"postfix map ${name}.db":` resource and replace it by adding the `notify  => $manage_notify` parameter.  This serves the dual purpose of ensuring that the generated map file has the correct permissions (as the permissions will not be changed by the `postmap` command if the file already exists) and ensures that the map file contents are regenerated if it is removed without the source map being touched.

**Comment by raphink** [comment]
OK. Can you file a PR for that please?
