### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by ghoneycutt** [camptocamp/puppet-postfix#173]
Since the module is now using data types and no longer supports Puppet v3, could you please bump to the next major version and release a tag for v2.0.0.

**Comment by func0der** [comment]
Yeah. Better soon than later, because the statement in forge that his module support Puppet 3 is simply false.

**Comment by bagasse** [comment]
It would be nice if you can publish a new version on the puppet forge as well, there is some new params that are missing on the published version.

**Comment by func0der** [comment]
What's the status on this one?

**Comment by raphink** [comment]
Version 1.6.0 was released in August, so I'm guessing this can be closed.

**Comment by ghoneycutt** [comment]
@raphink This still applies and should be left open. Please update the metadata to show that the module no longer supports Puppet 3 and release 2.0.0.
