### ISSUE TITLE
parameter class $mynetworks is not included into main.cf

### ISSUE THREAD

**Issue by lzecca78** [camptocamp/puppet-postfix#180]
I am changing the class parameter inside the main class : 

```
class{'::postfix':
   mynetworks => 'whatever'
}
```
Once that i run puppet, nothing happens, still preserve the defaults string '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128'.
I solved it changing class class postfix::files adding mynetworks,  i open a pull request for this as soon as possible

**Comment by mrintegrity** [comment]
@lzecca78 can you post your changes please, having the same issue

**Comment by lzecca78** [comment]
@mrintegrity : here the pr i did but was not accepted: https://github.com/camptocamp/puppet-postfix/pull/181/files
