### ISSUE TITLE
relayhost not working

### ISSUE THREAD

**Issue by ploeghvander** [camptocamp/puppet-postfix#187]
Hi, the resource relayhost is not working; I got this code;

  class { postfix:
    relayhost => 'smtp.server.nl',
    mailman => true,
  }

resource mailman is working correctly. relayhost is not.

**Comment by nohaj** [comment]
Hello,

With hiera, relayhost is also not working :

postfix::relayhost: "mailhost"

Regards,

Johan

**Comment by ploeghvander** [comment]
Sorry, wrong syntax used. I have this now;

include postfix
postfix::config {
    'relay_domains':   ensure => 'present',  value => 'localhost host.foo.com';
    'mynetworks':      ensure => 'present',  value => '127.0.0.1/8, 37.94.0.0/16';
}
