### ISSUE TITLE
Wrong value for mailx_package on Debian 9

### ISSUE THREAD

**Issue by moritzrempel** [camptocamp/puppet-postfix#190]
Hi,

in manifests/parameters.pp the value of mailx_package is set depending on Distribution and release.
For Debian it matches lsbdistcodename against /sarge|etch|lenny/ which also matches str**etch** while it must not. Adding anchors to the pattern should fix it.

Thanks and regards,
Moritz

**Comment by dploeger** [comment]
Is fixed in 1.6.0

**Comment by pillarsdotnet** [comment]
@moritzrempel @dploeger I guess we can close this issue?

**Comment by moritzrempel** [comment]
Sure, go ahead.

**Comment by pillarsdotnet** [comment]
Um, I'm not authorized to close.  The issue owner can close, and the repo administrator can close, but I'm neither.
