### ISSUE TITLE
Relayhost with box brackets not possible

### ISSUE THREAD

**Issue by AnonJo** [camptocamp/puppet-postfix#191]
By the Postfix documentation (http://www.postfix.org/postconf.5.html#relayhost) it should be possible to use box brackets for not using the MX record in the relayhost configuration.

Using this option fails with the following error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Wrong value for $relayhost at .../modules/postfix/manifests/mta.pp:34 on node ..

**Comment by ubellavance** [comment]
Could you provide more information (your actual manifest)?  Have you tried escaping them?
