### ISSUE TITLE
add templates for sles12 sp2 and sp3

### ISSUE THREAD

**Issue by matthiasritter** [camptocamp/puppet-postfix#197]
Hi,
can you add the templates for sles12 sp2 and sp3?
I've already created both, which I could send you...
Thanks and regards,
Matthias

**Comment by ubellavance** [comment]
The best way to have something implemented is via a pull request. Most maintainers are very busy and don't have much time to implement changes themselves, they often don't even have much time just to approve pull requests.

**Comment by matthiasritter** [comment]
unfortunately I can't create a pull-request :-) thats the reason why I created this issue

**Comment by matthiasritter** [comment]
sorry, I've forget to fork
