### ISSUE TITLE
inet_interfaces duplicate definition?

### ISSUE THREAD

**Issue by dafydd2277** [camptocamp/puppet-postfix#210]
I set a profile with these entries:

```
class profile::baseline::linux::postfix {

  include postfix

  postfix::config { 'relayhost':
    ensure => present,
    value  => "[RELAY].${facts['domain']}",
  }

  postfix::config { 'root_mail_recipient':
    ensure => present,
    value  => '[ADDRESS]',
  }

  postfix::config { 'inet_interfaces':
    ensure => present,
    value  => 'localhost',
  }
}
```

This error was produced:

```
[root@[HOST]~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Postfix::Config[inet_interfaces] is already declared in file /etc/puppetlabs/code/environments/[ENV]/modules/postfix/manifests/files.pp:85; cannot redeclare at /etc/puppetlabs/code/environments/[ENV]/site/profile/manifests/baseline/linux/postfix.pp:23 at /etc/puppetlabs/code/environments/[ENV]/site/profile/manifests/baseline/linux/postfix.pp:23:3 on node [NODE]
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by raphink** [comment]
You need to pass `inet_interfaces` as a parameter to the `postfix` class.

**Comment by dafydd2277** [comment]
Yah, I figured that out later.

**Comment by SiteDesignUSA** [comment]
> 
> 
> You need to pass `inet_interfaces` as a parameter to the `postfix` class.

Would you possibly, could you perhaps explain what you wrote means? An example block of code would be excellent also.

Thank you.

**Comment by SiteDesignUSA** [comment]
For those who find this through google like I did, this is what you need to do:

Do not use:
`include postfix`

That uses all the defaults. If you want to change any of the parameters listed on the CamptoCamp Puppet-Postfix  page use the example below.

Use this instead to override the default parameters:
` 
class { '::postfix':
inet_interfaces => 'localhost',
inet_protocols  => 'ipv4',
root_mail_recipient => "$mailaliases",
}
`

Now, you can override all those parameters on the README page.

The docs are seriously wanting for those of us who are just starting. After these past 6 hours of searching, I found the answer by a lot of trial and error.

Hope I saved someone time.

**Comment by ubellavance** [comment]
This is what I in my config file: 

```
  include selinux

  class { 'postfix':
    mta                 => true,
    satellite           => false,
    relayhost           => 'direct',
    mynetworks          => '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 192.168.x.xx/32 192.168.xx.xx/24 192.168.x.xx/24',
    root_mail_recipient => 'root@domain.com',
    smtp_listen         => 'all',
    inet_interfaces     => 'all',
    ldap                => false,
  }
```

Would it have helped if I had shared that before? The README file is clear for me, but if you feel like something is missing, feel free to create a pull request for the README file. Or you can tell us here what you would like to be added or changed to the README file and maybe here will have time to do the pull request.

**Comment by SiteDesignUSA** [comment]
@ubellavance 
Thank you for the reply. I have just started to work with Puppet and have, effectively, no Ruby experience so "passing parameter" was greek to me. Now I understand what "passing parameters" is. 

The problem with the postfix docs, if you slow down and actually read them like a novice (like me) would, you'll see that they say to 

<pre>
include postfix

postfix::config { 'relay_domains':
  ensure  => present,
  value   => 'localhost host.foo.com',
}
</pre>

then just skip over what most other README files do, (Which is how I stumbled on the answer. I gave up on postfix and started another module and they explained if a user wanted to change defaults to use class { 'YourClassHere': parameters, etc.)

So, for example, the voxpupuli/php Puppet Module page has the following- 

link: https://forge.puppet.com/puppet/php#voxpupuliphp-puppet-module
================================================================
**Usage**

Quickest way to get started is simply include'ing the php class.

`include '::php'`

Or, you can override defaults and specify additional custom configurations by declaring class { '::php': } with parameters:

<pre>
class { '::php':
  ensure       => latest,
  manage_repos => true,
  fpm          => true,
  dev          => true,
  composer     => true,
  pear         => true,
  phpunit      => false,
}
</pre>
===============================================================


I hope you can see how someone just starting out with Puppet might spend an inordinate amount of time fighting to understand what to do if the postfix module was the first ( or even 5th or 6th) module they started with.
