### ISSUE TITLE
Error under debian 10/Buster (future stable)

### ISSUE THREAD

**Issue by bb2k** [camptocamp/puppet-postfix#218]
Hello i tried to puppetize a buster/10 debian and i got this error.  This config work fir a debian 8 jessie or 9 stretch.
Thx !

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /etc/puppetlabs/code/environments/production/modules/augeas/manifests/lens.pp:61:24 at /etc/puppetlabs/code/environments/production/modules/postfix/manifests/augeas.pp:13 on node v-templatetest.xxx.fr`
```

Here is my hiera config

```
postfix::satellite: true
postfix::myorigin: 'localdomain.local'
postfix::inet_interfaces: 'localhost'
postfix::inet_protocols: 'ipv4'
postfix::relayhost: 'smtp.xxx.fr'
postfix::root_mail_recipient: 'admin-xxx@uhb.fr'

```

**Comment by raphink** [comment]
The error indicates that the `$::augeasversion` fact was not defined. This probably means Augeas is not properly installed on your system. Which version (and mostly packaging) of Puppet do you use?

**Comment by Elbandi** [comment]
new facter detect the augeas version from augparse cmd line (https://github.com/puppetlabs/facter/blob/master/lib/src/facts/resolvers/augeas_resolver.cc). you need install augeas-tools package

**Comment by vegaaz** [comment]
Thanks @Elbandi !
