### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by lelutin** [camptocamp/puppet-postfix#227]
Hi there!

We've started using your module since it's doing what we want to do with postfix (at least so far).

However, the latest release, 1.6.0, happened more than a year ago. There's been a good amount of work that was done since then, and some of the commits fix problems with puppet 4.x

Would it be time for a new release?

**Comment by raphink** [comment]
Yes indeed. I just want to finish sorting out the chroot issue (cf #224) and then I think I can cut a release.

**Comment by lelutin** [comment]
@raphink ah! ok great. thanks for the quick answer :)

need any help figuring things out with that other issue?

**Comment by raphink** [comment]
If you have a useful opinion to get things moving, sure.

**Comment by raphink** [comment]
Just tagged release 1.7.0. Build it ongoing https://travis-ci.org/camptocamp/puppet-postfix/builds/449344788
