### ISSUE TITLE
transport map : unmanaged resources purge

### ISSUE THREAD

**Issue by fenixwanamaker** [camptocamp/puppet-postfix#251]
The resource **postfix::transport** does not handle unmanaged entries in the /etc/postfix/transport file

steps to reproduce the issue :

1. manually add an entry to the file /etc/postfix/transport ( e.g : **gmail.com : discard** )
2. apply the puppet catalog, using the **postfix::transport** resource, and a configuration which doesn't include gmail.com
3. the manually added entry is still present after the puppet run

**Comment by raphink** [comment]
That is right, and it is the expected behavior. This module allows you to manage the configuration in a granular way, but does not purge unmanaged entries at the moment.
