### ISSUE TITLE
Unknown resource type: 'mailalias'

### ISSUE THREAD

**Issue by hoene** [camptocamp/puppet-postfix#258]
Using the latest foreman and puppet, I get the error

Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'mailalias' (file: .../modules/postfix/manifests/mailalias.pp, line: 31, column: 3) (file: ../modules/postfix/manifests/files.pp, line: 106) on node tue
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by hoene** [comment]
puppet --version
6.7.2

**Comment by raphink** [comment]
If you're not using the Puppet AIO installer, you need to install the `puppetlabs/mailalias_core` module when using Puppet 6+.

**Comment by tuxmea** [comment]
@hoene with Puppet 6 many types/providers have been removed from puppet core and placed into modules.
See our Puppefile (https://github.com/example42/psick/blob/updates/Puppetfile#L12)
