### ISSUE TITLE
new release on forge

### ISSUE THREAD

**Issue by tuxmea** [camptocamp/puppet-postfix#266]
Hi,

several issues have been fixed since 1.8.0 was released.
Can we have at least a patchlevel release on forge?

Thank you,
Martin

**Comment by bastelfreak** [comment]
We triggered a release today https://forge.puppet.com/camptocamp/postfix

**Comment by alexjfisher** [comment]
Fixed in https://github.com/camptocamp/puppet-postfix/pull/265
