### ISSUE TITLE
Wrong tag on release 1.10.0

### ISSUE THREAD

**Issue by chrekh** [camptocamp/puppet-postfix#276]
The commit for Release 1.10.0 is tagged 0.10.0
That's probably just a mistake. 
Perhaps it's best to leave the tag 0.10.0 and just add tag 1.10.0 also.

**Comment by raphink** [comment]
Thanks, I will do that.

**Comment by raphink** [comment]
I just tagged 1.10.0 and removed the 0.10.0 tag as it's really useless and confusing.
