### ISSUE TITLE
Virtual not accepting regexp

### ISSUE THREAD

**Issue by headyj** [camptocamp/puppet-postfix#282]
Hello,

I try to add virtuals using regexp, but it seems to be broken. I tried multiple ones without success, including the example here (PR was never merged, by the way): https://github.com/camptocamp/puppet-postfix/pull/116. The result is always the same:

`/Stage[main]/Profile::Massmail/Postfix::Virtual[/.+@.+/]/Augeas[Postfix virtual - /.+@.+/]: Could not evaluate: Save failed, see debug output for details`

I have latest versions of the modules, including augeas.

**Comment by raphink** [comment]
Can you post the code you're using please?
