### ISSUE TITLE
Minimal MTA setup

### ISSUE THREAD

**Issue by TandMelk** [camptocamp/puppet-postfix#284]
Using the *simple usage* on the README;
```
include postfix
postfix::config { 'relay_domains':
  ensure  => present,
  value   => 'localhost host.foo.com',
}
```

Receiving the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Postfix::Params]:
  expects a value for parameter 'mailx_package'
  expects a value for parameter 'restart_cmd'
  expects a value for parameter 'master_os_template'
  expects a value for parameter 'aliasesseltype'
  expects a value for parameter 'seltype' at
```

Trying to setup a minimal MTA, to replace ssmtp, since I'm not using any of those functionalities, please suggest the minimal MTA setup.

Puppet version: **4.8.2**
Puppet-postfix version: **1.10.0**
Debian version: **Debian GNU/Linux 10 (buster)**

**Comment by ubellavance** [comment]
Which version of Puppet are you using? Which version of the module?

**Comment by TandMelk** [comment]
@ubellavance I'm using Puppet version 4.8.2. The [forge website](https://forge.puppet.com/camptocamp/postfix) indicates that Puppet > 4 is supported (`Puppet >= 4.0.0 < 7.0.0`). Also, I'm using the latest module version; `1.10.0`.

**Comment by ubellavance** [comment]
Ok, not sure if it's related, but Debian is not in the list of the supported Linux distributions on the Forge.

**Comment by igalic** [comment]
so perhaps it's time for a new release?

**Comment by raphink** [comment]
Did you [migrate your site `hiera.yaml` to Hiera 5](https://puppet.com/docs/puppet/6.17/hiera_migrate.html) already?
