### ISSUE TITLE
regex check for mynetworks should allow multiple values

### ISSUE THREAD

**Issue by ghost** [camptocamp/puppet-postfix#44]
The regex check used to validate the mynetworks setting does not currently allow for multiple values. For instance, I'd like to end up with: 

```
mynetworks = 10.12.0.0/16 10.22.0.0/16 127.0.0.0/8
```

Easy fix would be changing the regex_check in manifests/mta.pp to allow for multiple values.

**Comment by raphink** [comment]
Fixed by PR #80
