### ISSUE TITLE
postfix doesn't restart in different queue_directory

### ISSUE THREAD

**Issue by eumel8** [camptocamp/puppet-postfix#53]
puppet 2.7.11, ubuntu 12.04 LTS
I try to install postfix with a specific configuration:

```puppet
class { 'postfix':
     smtp_listen     => 'all',
}
postfix::config { "mynetworks": value => "192.168.0.0/24, 127.0.0.1" }
postfix::config { "relay_domains": value => "localhost" }
postfix::config { "myhostname": value => "mail.cloud.local"}
postfix::config { "queue_directory": value => "/data/mail"}
postfix::config { "mydestination": value => "mail.cloud.local, localhost"}
```

Mount point and directory are configured previously. After reboot and puppet run postfix is running but not usable:
```
Jul 15 13:28:06 mail postfix/master[13347]: fatal: open lock file /var/lib/postfix/master.lock: unable to set exclusive lock: Resource temporarily unavailable
```

Maybe postfix was started with standard configuration and later it was not possible to reach the lock file. A workaround described in https://github.com/eumel8/puppet-postfix/commit/c2024067dcc0b60ec6fa7b10891997aca5363372 but it's not really the solution.

**Comment by mcanevet** [comment]
@eumel8 I think https://github.com/camptocamp/puppet-postfix/commit/503235889db4ebf8f8a737e8b312e1a13d3b37e0 fixed this bug, so I close this issue. Feel free to reopen if it is still relevant.
