### ISSUE TITLE
Character whitelist for destination e-mail addresses

### ISSUE THREAD

**Issue by ghost** [camptocamp/puppet-postfix#65]
The whitelist for characters in e-mail addresses in postfix_canonical.aug is sadly lacking.  In my particular case, it didn't include "+", but https://tools.ietf.org/html/rfc2822 also specifies that quite a number of other non-alpha-numeric characters are also valid (section 3.2.4).  I can confirm that adding + to the regex works, so the rest are probably ok too.

**Comment by raphink** [comment]
Can you provide a minimal example of code that fails please?

**Comment by craigmiskell** [comment]
include augeas 
      include postfix
      postfix::hash { '/etc/postfix/canonical':
        ensure => present,
      }
      postfix::canonical { 'root':
        ensure      => present,
        file        => '/etc/postfix/canonical',
        destination => "root+${::hostname}@catalyst.net.nz",
      }

**Comment by raphink** [comment]
I see. Could you send a PR against the lens, as well as corresponding unit tests for the lens please?
