### ISSUE TITLE
Quoted alias_maps fail on RHEL6/postfix 2.6.6

### ISSUE THREAD

**Issue by phathocker** [camptocamp/puppet-postfix#69]
Quotes around alias_maps on RHEL6/postfix 2.6.6 don't work. Do they on other OSes?

<pre>
-alias_maps = hash:/etc/aliases
+alias_maps = "hash:/etc/aliases, ldap:/etc/postfix/ldap-aliases.cf"
</pre>

Postfix error in /var/log/maillog:

<pre>
Feb  4 16:26:07 ncc16405 postfix/smtpd[9529]: fatal: unsupported dictionary type: "hash
Feb  4 16:26:08 ncc16405 postfix/master[9523]: warning: process /usr/libexec/postfix/smtpd pid 9529 exit status 1
Feb  4 16:26:08 ncc16405 postfix/master[9523]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
</pre>

**Comment by phathocker** [comment]
http://www.postfix.org/postconf.5.html:

alias_maps (default: see "postconf -d" output)
The alias databases that are used for local(8) delivery. See aliases(5) for syntax details. Specify zero or more "type:name" lookup tables, separated by whitespace or comma. Tables will be searched in the specified order until a match is found. Note: these lookups are recursive.

The default list is system dependent. On systems with NIS, the default is to search the local alias database, then the NIS alias database.

If you change the alias database, run "postalias /etc/aliases" (or wherever your system stores the mail alias file), or simply run "newaliases" to build the necessary DBM or DB file.

The local(8) delivery agent disallows regular expression substitution of $1 etc. in alias_maps, because that would open a security hole.

The local(8) delivery agent will silently ignore requests to use the proxymap(8) server within alias_maps. Instead it will open the table directly. Before Postfix version 2.2, the local(8) delivery agent will terminate with a fatal error.

Examples:

alias_maps = hash:/etc/aliases, nis:mail.aliases
alias_maps = hash:/etc/aliases

**Comment by raphink** [comment]
Discussion on this is in #74

**Comment by mcanevet** [comment]
@phathocker I think https://github.com/camptocamp/puppet-postfix/pull/74 fixed this bug, so I close this issue. Feel free to reopen if it is still relevant.

**Comment by phathocker** [comment]
Thanks!
