### ISSUE TITLE
Unable to handle pcre mappings

### ISSUE THREAD

**Issue by bdellegrazie** [camptocamp/puppet-postfix#76]
Hi,

We use pcre_table(5) format for sender_canonical_maps which doesn't require postmap execution and has a slightly different format (which the existing lens does not support).

Would it be possible to:
1) Modify the hash command to support a type and action (defaulting to hash, postmap execution) but supporting null/noop for the action
2) Modify the postfix_canonical lens, or supply an additional one to support pcre_table format?
And use that lens as appropriate?

At present we are managing this as a separate file so this is a 'nice to have'

**Comment by raphink** [comment]
It definitely sounds possible, but I don't think we have an interest in coding it ourselves. A PR is welcome, unless you're interested in purchasing development from our team.

Just a question: is this syntax exclusive, or can a file contain both syntaxes?

**Comment by bdellegrazie** [comment]
Hi Raphael,

Syntax is exclusive (regexp target) the hash type changes (to pcre: instead
of hash:) and pcre hashes do not require postmap usage (to the best of my
knowledge).

Thanks,

Brett



On 18 February 2015 at 09:52, Raphaël Pinson <notifications@github.com>
wrote:

> It definitely sounds possible, but I don't think we have an interest in
> coding it ourselves. A PR is welcome, unless you're interested in
> purchasing development from our team.
>
> Just a question: is this syntax exclusive, or can a file contain both
> syntaxes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camptocamp/puppet-postfix/issues/76#issuecomment-74838408>
> .
>



-- 
Kind regards,

Brett Delle Grazie

**Comment by raphink** [comment]
OK. In that case, we need a new lenses for that type of files.
