### ISSUE TITLE
changing portbind in master.cf no effect (Centos6.6/7)

### ISSUE THREAD

**Issue by wouteroostervld** [camptocamp/puppet-postfix#81]
Using:

    class { '::postfix':
        inet_interfaces => $inet_interfaces,
        mynetworks      => join($mynetworks, ','),
        smtp_listen     => 'all',
        mta             => true,
        relayhost       => 'direct'
    }

With $inet_interfaces = all.

The reload issued by puppet-postfix is not enough to make postfix listen on 0.0.0.0:

    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                  ::1:25                   :::*     
    tcp    LISTEN     0      100            127.0.0.1:25                    *:*     
    [vagrant@relay-2008 ~]$ service postfix reload
    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                  ::1:25                   :::*     
    tcp    LISTEN     0      100            127.0.0.1:25                    *:*     
    [vagrant@relay-2008 ~]$ sudo service postfix reload 
    Reloading postfix:                                         [  OK  ]
    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                  ::1:25                   :::*     
    tcp    LISTEN     0      100            127.0.0.1:25                    *:*     
    [vagrant@relay-2008 ~]$ sudo postfix reload
    postfix/postfix-script: refreshing the Postfix mail system
    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                  ::1:25                   :::*     
    tcp    LISTEN     0      100            127.0.0.1:25                    *:*     
    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                  ::1:25                   :::*     
    tcp    LISTEN     0      100            127.0.0.1:25                    *:*     
    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                  ::1:25                   :::*     
    tcp    LISTEN     0      100            127.0.0.1:25                    *:*

Restart works:
     
    [vagrant@relay-2008 ~]$ sudo service postfix restart
    Shutting down postfix:                                     [  OK  ] 
    Starting postfix:                                          [  OK  ]
    [vagrant@relay-2008 ~]$ ss -tulpn | grep :25
    tcp    LISTEN     0      100                   :::25                   :::*     
    tcp    LISTEN     0      100                    *:25                    *:*     
    [vagrant@relay-2008 ~]$ 

Suggestion: change "/etc/init.d/postfix reload" to "service postfix restart" in service.pp.

**Comment by raphink** [comment]
Fixed by #78

**Comment by wouteroostervld** [comment]
I don't think this fixes the issue. When changing master.cf postfix needs a restart instead of a reload. Please reopen.
