### ISSUE TITLE
mynetworks parameter ignored?

### ISSUE THREAD

**Issue by mentalblock** [camptocamp/puppet-postfix#88]
I haven't delved deeply into the puppet code itself, but I find that the $mynetworks parameter to the main class at https://github.com/camptocamp/puppet-postfix/blob/master/manifests/init.pp#L85 is ignored. I ended up having to specify the 'mynetworks' parameter as a postfix::config item instead. Anyone else having this problem?

I had this snippet in hiera:

postfix::myorigin: '$mydomain'
postfix::mynetworks: '10.90.0.0/16, 10.91.0.0/16, 127.0.0.0/8, 10.96.0.0/16'

The 'mynetworks' parameter was not being created yet the 'myorigin' parameter was.

**Comment by mcanevet** [comment]
@mentalblock `mynetwork` is used here : https://github.com/camptocamp/puppet-postfix/blob/master/manifests/mta.pp#L51 which is included here : https://github.com/camptocamp/puppet-postfix/blob/master/manifests/init.pp#L152, so you have to set `mta => true` when declaring the `postfix` class
