### ISSUE TITLE
fatal: bind 127.0.0.1 port 25: Address already in use

### ISSUE THREAD

**Issue by rauchrob** [camptocamp/puppet-postfix#90]
I have set up a couple of Ubuntu 14.04 machines with Postfix, simply by including this module without further parameters. The following Puppet run is succesful, but the postfix service is *not* running afterwards. There is an error message in `/var/log/mail.err`:

```
Apr 14 10:10:24 wsntbk13 postfix/master[22826]: fatal: bind 127.0.0.1 port 25: Address already in use
```

After the second Puppet run, everything works as expected.

**Comment by rauchrob** [comment]
The problem probably is, that we are calling `service postfix reload` to restart Postfix on configuration changes. Appparently, this will not work in every case.

I'd suggest to do a hard restart (i.e. stop && start) on configuration changes per default, and additionally provide an Exec like, e.g.

```puppet
exec { 'reload postfix configuration':
    command     => $::postfix::params::reload_cmd,
    refreshonly => true,
}
```

which can then be triggered from, e.g. `puppet::files` by adding correpsonding `notify` attributes to those File resources.

An even easier approch could be to do a hard `restart`, if we detect that a `reload` did not succeed.

**Comment by alexjfisher** [comment]
I've run into the same problem on RHEL 6.6 with the following manifest
```puppet
include ::augeas
class { 'postfix':
  satellite   => true,
  smtp_listen => '127.0.0.1',
  relayhost   => 'relayhost.example.com',
}
```
I have to run puppet twice for this manifest to work.  There are no errors in the puppet logs, but the reload fails and after the puppet run is completed, the service is in a 'stopped' state.  Below are the postfix logs.
```
Apr 29 13:45:11 mailhost postfix/postfix-script[12268]: refreshing the Postfix mail system
Apr 29 13:45:11 mailhost postfix/master[1506]: reload -- version 2.6.6, configuration /etc/postfix
Apr 29 13:45:11 mailhost postfix/master[1506]: warning: service 127.0.0.1:smtp: ignoring inet_interfaces change
Apr 29 13:45:11 mailhost postfix/master[1506]: warning: to change inet_interfaces, stop and start Postfix
Apr 29 13:45:11 mailhost postfix/master[1506]: fatal: bind 127.0.0.1 port 25: Address already in use
```

@rauchrob - Have you thought about creating a PR with one of your suggestions?

Thanks,
Alex

**Comment by rauchrob** [comment]
@mcanevet - What do you think of integrating the acceptance tests I have prepared in rauchrob/puppet-postfix@bde74d8acdf1a830f3d5dddbf2d92555ca1da1ed?
