### ISSUE TITLE
Hash files using regexp

### ISSUE THREAD

**Issue by jordiclariana** [camptocamp/puppet-postfix#92]
Hi,

I see that using regexp in hash files like virtual, transport and canonical is not suported due the augeas len. I don't know enough about augeas to implement it. Is there any plan to implement that in the augeas or any alternative to achive this?

Thanks.

**Comment by mcanevet** [comment]
ping @raphink

**Comment by OlivierLM** [comment]
+1 ping @raphink ?

**Comment by markeganfuller** [comment]
I had a look at trying to get regexes to work via augeas and gave up in the end, instead I ended up doing the following:

```yaml
profile::postfix::virtual:
    - "/rob.*/ root"
```

```puppet
$virtual = lookup('profile::postfix::virtual',
{
  value_type    => Array,
  default_value => [],
  merge         => 'unique',
})

# A bit of a hack to work around the fact augeaus really doesn't want to
# use regexes in key names
#
# Note the double quote within double quote (which works here)
postfix::hash { '/etc/postfix/virtual':
  content => "${ $virtual.join("\n") }\n",
}
```

**Comment by raphink** [comment]
@jordiclariana 	@OlivierLM 	do you have a specific example of the syntax you'd like to pass?

**Comment by OlivierLM** [comment]
As an example, this virtual map shall work :
```
/^.*-owner\@liste\.unicaen\.fr$/ sympabounce:
/^bounce\+.*/ sympabounce:
/^.+(?<!-owner)\@liste\.unicaen\.fr$/ sympa:

```

**Comment by raphink** [comment]
@OlivierLM 	ok, and what would the Puppet code you'd expect to use for that?

**Comment by OlivierLM** [comment]
```
  postfix::transport {'/^.*-owner\@liste\.unicaen\.fr'
    ensure      => present,
    destination => 'sympabounce',
  }

```

**Comment by OlivierLM** [comment]
Don't know hox to try this easily :(

**Comment by raphink** [comment]
Fixed in https://github.com/camptocamp/puppet-postfix/pull/225
