### ISSUE TITLE
postfix::augeas should include ::augeas

### ISSUE THREAD

**Issue by alexjfisher** [camptocamp/puppet-postfix#93]
Hello.
I've just started looking at this module.
I'm getting an error when applying this simple manifest.

``` puppet
class { 'postfix':
  satellite   => true,
  smtp_listen => '127.0.0.1',
  relayhost   => '[mailout.example.com]',
}
```

```
Error: Evaluation Error: Error while evaluating a Function Call, You must declare the augeas class before using augeas::lens at /tmp/modules/augeas/manifests/lens.pp:34:5
```

Is the correct fix as simple as including ::augeas at the top of postfix::augeas?

Versions used:
camptocamp-augeas (v1.2.3)
camptocamp-postfix (v1.2.1)

Thanks,
Alex

**Comment by ubellavance** [comment]
Is it normal that this fix isn't in the latest version?

**Comment by lingfish** [comment]
I've just hit this bug too -- wondering when https://github.com/camptocamp/puppet-augeas/pull/45 will be put into a release.

**Comment by raphink** [comment]
Just tagged a 1.5.0 release. Sorry for the delay.

**Comment by alexjfisher** [comment]
I've just started using this module again, and can confirm this is fixed with the latest releases.
